language: python
dist: trusty
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script: make html
deploy:
  provider: pages
  skip-cleanup: true  # Keeps the built files so they can be deployed
  github-token: $GITHUB_TOKEN
  keep-history: true  # Disables force push
  local-dir: _build/html
  target-branch: master
  on:
    branch: src
