---

- hosts: web-server
  remote_user: ubuntu

  tasks:
  - include_vars:
      file: 'config/webserver_vars.yml'

  - name: Ensure required packages are installed
    apt:
      name: "{{ item }}"
      state: latest
      cache_valid_time: 600
    with_items:
      - python3
      - python3-pip
      - git
      - curl
    become: yes

  - name: Ensure mount point dir exists
    file:
      state: directory
      path: "{{ web_vol_mnt_point }}"
      owner: ubuntu
      group: ubuntu
    become: yes

  - name: Mount the website data
    mount:
      state: mounted
      src: "{{ web_data_vol_uuid }}"
      name: "{{ web_vol_mnt_point }}"
      fstype: ext4
      opts: defaults
      dump: 0
      passno: 2
    become: yes

  - name: One more time just to make sure owner and group are set
    file:
      state: directory
      path: "{{ web_vol_mnt_point }}"
      owner: ubuntu
      group: ubuntu
    become: yes

  - name: Checkout the Caddyfile gist
    git:
      repo: https://gist.github.com/a84868f1bba4c2a9cb42c43cca7966c2.git
      dest: "{{ gist_dir }}"

  - name: Create dir /etc/caddy
    file:
      state: directory
      path: "{{ caddy_conf_dir }}"
      owner: root
      group: root
    become: yes

  - name: Add link to Caddyfile in /etc/caddy/
    file:
      state: link
      src: "{{ gist_dir }}/Caddyfile"
      dest: "{{ caddy_conf_path }}"
    become: yes

  - name: Install Caddy now
    shell: "{{ update_caddy_cmd }}"
    become: yes

  - name: Give Caddy permissions to listen to lower ports (80)
    command: setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/caddy
    become: yes

  - name: Start Caddy now
    shell: "nohup caddy -conf {{ caddy_conf_path }} &"

  #
  #  Cron Jobs
  #
  - name: Set up cron job to download the current version of Caddy
    cron:
      name: "Update Caddy"
      job: "{{ update_caddy_cmd }}"
      state: present
      special_time: weekly
      user: root
    become: yes

  - name: Cron job to start Caddy on restart
    cron:
      name: "Start Caddy"
      job: "nohup caddy -conf {{ caddy_conf_path }} &"
      state: present
      special_time: reboot
      user: ubuntu
    become: yes

  - name: Cron job to check in with Dead Man's Snitch
    cron:
      name: "Dead Man's Snitch check-in"
      job: "/usr/bin/curl https://mikemabey.com &> /dev/null && /usr/bin/curl https://nosnch.in/ee711a27a4 &> /dev/null"
      state: present
      minute: "*/10"
      user: ubuntu
